### ISSUE TITLE
Can you please create a cursor set with the name Ocean?

### ISSUE THREAD

**Issue by krishhandro** [ful1e5/bibata#25]
I suggest a cursor theme named Ocean with the `#438de6` as the main colour. You can name it anything. A set of cursors with this default folder icon colour of Gnome would be awesome.

**Comment by ful1e5** [comment]
@krishhandro Thanks for sharing your suggestion! You can customize Bibata on https://www.bibata.live/studio using the attached config. I've created this web app for easy customization and downloading with your preferred colors. 

At the moment, I don't have plans to add "Ocean" colors to the [Original Repository](https://github.com/ful1e5/Bibata_Cursor) as it already offers a variety of color options and variants, and I aim to keep it streamlined. 

However, if there is significant interest from users, I'd be open to exploring this in the future. Appreciate your input, and thanks for reporting the feature!

### Config

**Base:** `#438de6`
**Outline:** `#3e3e3e`
**Watch Background:** `#222222`

![image](https://github.com/ful1e5/bibata/assets/24286590/93206e74-dc06-49ef-9ecf-bce2fb76cddf)
![image](https://github.com/ful1e5/bibata/assets/24286590/bbe95df8-8fd0-4e29-90f2-03522db8ab2d)

**Comment by krishhandro** [comment]
@ful1e5 Thank you for the response. I was not aware of this web app. I will surely try it out. :)

**Comment by krishhandro** [comment]
I am closing this issue. Thanks again.

**Comment by ful1e5** [comment]
@krishhandro, thanks for sponsoring. I really appreciate it.
