### ISSUE TITLE
Website isn’t working :/

### ISSUE THREAD

**Issue by Escabt** [ful1e5/bibata#33]
It won’t let me download any type of cursor from the bibata live website, it stays stuck on processing/authorizing. Didn’t know where else to go about this, hopefully it fixes soon!

**Comment by ful1e5** [comment]
The download issue on the [bibata.live](https://www.bibata.live/studio) was due to a server error with Prisma’s `targetBinaries` configuration.

I've updated them for Vercel. You should be able to download now. Enjoy! :)
